### ISSUE TITLE
Undefined Reference To yywrap

### ISSUE THREAD

**Issue by lexxmark** [meyerd/flex-bison-example#3]
Hi meyerd,

I referenced to your project in winflexbison project and some users have issues.
See https://sourceforge.net/p/winflexbison/tickets/5/

The main reason is that we should link with -lfl option and thus should have fl.lib file.
Could you avoid dependency from fl library by declaring %option noyywrap in lexer file?

Regards,
   Alex

**Comment by meyerd** [comment]
Hi Alex,

updated the changes. Thanks for the hint.

Cheers.
